name: 'List Changed Directories'
description: 'List directories that have changed in the latest commit'
inputs:
  target-file:
    description: 'Target file to look for in directories'
    required: false
    default: ''
outputs:
  changed-directories:
    description: 'List of changed directories'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: 'List changed directories'
      id: list-changed-directories
      run: |
        #!/bin/sh
        # Find changed directories
        CHANGED_DIRECTORIES=$(git diff --name-only HEAD~1 HEAD | xargs -I{} dirname {} | sort | uniq)
        echo "changed-directories=$CHANGED_DIRECTORIES" >> $GITHUB_OUTPUT