# action.yml
inputs:
  # ... existing inputs ...
  exclude:
    description: 'Folders to exclude (one per line, wildcard patterns)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Detect changed folders
      id: changed_folders
      shell: bash
      run: |
        echo "::group::Detecting changed folders"
        EXCLUDE_ARGS=""
        if [[ -n "${{ inputs.exclude }}" ]]; then
          EXCLUDE_ARGS="--exclude ${{ inputs.exclude }}"
        fi

        FOLDERS_RAW=$(python "$GITHUB_ACTION_PATH/changed_folders.py" \
          "${{ inputs.time_interval }}" \
          "$EXCLUDE_ARGS")

        # Proper multiline output handling
        FOLDERS_JSON=$(jq -n --arg folders "$FOLDERS_RAW" '$folders | split("\n")')
        echo "folders=$FOLDERS_JSON" >> $GITHUB_OUTPUT

        if [ -z "$FOLDERS_RAW" ]; then
          echo "::notice::No folders changed. Exiting early."
          exit 0
        fi

        echo "Detected folders:"
        echo "$FOLDERS_RAW"
        echo "::endgroup::"