name: 'Changed Folders Runner'
description: 'Run custom commands or scripts for each changed folder based on a time interval.'
author: 'Your Name'

inputs:
  time_interval:
    description: 'Time interval to check for changes (e.g., "3 hours", "1 day").'
    required: true
    default: '1 day'
  commands:
    description: 'Commands to run for each folder, separated by newlines. Ignored if script is provided.'
    required: false
  script:
    description: 'Script to run for each folder. If provided, commands are ignored.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Detect changed folders
      id: changed_folders
      shell: bash
      run: |
        echo "::group::Detecting changed folders"
        FOLDERS=$(python changed_folders.py "${{ inputs.time_interval }}")

        if [ -z "$FOLDERS" ]; then
          echo "No folders changed in the last ${{ inputs.time_interval }}. Exiting early."
          exit 0
        fi

        echo "Detected folders: $FOLDERS"
        echo "folders=$FOLDERS" >> $GITHUB_OUTPUT
        echo "::endgroup::"

    - name: Run script or commands for each folder
      shell: bash
      run: |
        echo "::group::Running script/commands"
        for FOLDER in ${{ steps.changed_folders.outputs.folders }}; do
          echo "Processing folder: $FOLDER"
          export FOLDER="$FOLDER"

          if [ -n "${{ inputs.script }}" ]; then
            echo "Running script ${{ inputs.script }} for $FOLDER"
            chmod +x "${{ inputs.script }}"
            "${{ inputs.script }}" "$FOLDER"
          elif [ -n "${{ inputs.commands }}" ]; then
            while IFS= read -r CMD; do
              echo "Running: $CMD"
              eval "$CMD"
            done <<< "${{ inputs.commands }}"
          else
            echo "No script or commands provided. Skipping."
          fi
        done
        echo "::endgroup::"
